<?= view('web/_layout_top', get_defined_vars()) ?>
<section class="card">
  <div class="card-heading"><div><p>REGISTRATION</p><h2>Add a Studio</h2></div><span class="muted">A Studio maps to one paired Player installation</span></div>
  <?php if ($operators === []): ?><div class="alert error">Create an active operator before assigning a Studio.</div><?php endif ?>
  <?php if (array_filter($locations, static fn ($location): bool => $location->status === 'active') === []): ?><div class="alert error">Create an active Location before adding a Studio.</div><?php endif ?>
  <form method="post" action="<?= site_url('control/devices') ?>" class="form-grid">
    <?= csrf_field() ?><label>Studio name<input name="name" value="<?= esc(old('name')) ?>" placeholder="Studio 1" maxlength="120" required></label>
    <label>Location<select name="location_id" required><option value="">Choose an active Location</option><?php foreach ($locations as $location): if ($location->status !== 'active') continue; ?><option value="<?= esc($location->public_id) ?>" <?= (string) old('location_id') === (string) $location->public_id ? 'selected' : '' ?>><?= esc($location->name) ?> — <?= esc($location->code) ?></option><?php endforeach ?></select></label>
    <label>Timezone <span class="field-note">(optional override)</span><input name="timezone" value="<?= esc(old('timezone')) ?>" placeholder="Inherited from Location"></label>
    <label>Assigned operator<select name="assigned_user_id"><option value="">Unassigned</option><?php foreach ($operators as $operator): ?><option value="<?= $operator->id ?>" <?= (string) old('assigned_user_id') === (string) $operator->id ? 'selected' : '' ?>><?= esc($operator->name) ?> — <?= esc($operator->email) ?></option><?php endforeach ?></select></label>
    <div class="form-action"><button class="btn primary" type="submit">Create Studio</button></div>
  </form>
</section>
<section class="card">
  <div class="card-heading"><div><p>STUDIO DIRECTORY</p><h2>Registered Studios</h2></div><span class="count"><?= count($devices) ?> Studios</span></div>
  <form method="get" action="<?= site_url('control/devices') ?>" class="filter-row studio-filters"><input name="q" value="<?= esc($filters['q']) ?>" placeholder="Search Studio, Location, operator, or ID"><select name="location"><option value="">All Locations</option><?php foreach ($locations as $location): ?><option value="<?= esc($location->public_id) ?>" <?= $filters['location'] === $location->public_id ? 'selected' : '' ?>><?= esc($location->name) ?></option><?php endforeach ?></select><select name="status"><option value="">All statuses</option><?php foreach (['pending' => 'Waiting to pair', 'online' => 'Online', 'offline' => 'Offline', 'playing' => 'Playing', 'paused' => 'Paused', 'idle' => 'Idle', 'error' => 'Playback error'] as $value => $label): ?><option value="<?= $value ?>" <?= $filters['status'] === $value ? 'selected' : '' ?>><?= $label ?></option><?php endforeach ?></select><button class="btn primary" type="submit">Filter</button><a class="btn ghost" href="<?= site_url('control/devices') ?>">Reset</a></form>
  <?php if ($devices === []): ?><div class="empty">No Studios match the current filters.</div><?php else: ?><div class="device-grid"><?php foreach ($devices as $item): $device = $item['entity']; $location = $item['location']; ?>
    <article class="device-card"><div class="device-title"><span class="device-icon">▶</span><div><strong><?= esc($device->name) ?></strong><small><?= esc($location?->name ?: $device->location ?: 'No Location') ?><?= $location ? ' · ' . esc($location->code) : '' ?></small></div><span class="badge <?= esc($item['connection']) ?>"><?= esc(strtoupper($item['connection'])) ?></span></div>
      <dl><div><dt>Device ID</dt><dd title="<?= esc($device->public_id) ?>"><?= esc($device->public_id) ?></dd></div><div><dt>Lifecycle</dt><dd><?= esc(ucfirst($device->status)) ?></dd></div><div><dt>Playback</dt><dd class="playback-state"><span class="playback-dot <?= esc($item['playback']) ?>"></span><?= esc(ucfirst($item['playback'])) ?><?= $device->playback_schedule_id ? ' · ' . esc($device->playback_schedule_id) : '' ?></dd></div><div><dt>Assigned to</dt><dd><?= esc($item['assignedName']) ?></dd></div><div><dt>Version</dt><dd><?= esc($device->app_version ?: 'Not paired') ?></dd></div><div><dt>Media protection</dt><dd><?= $device->ldg_version === 'ldg-v1' ? 'LDG v1 ready' : 'Player update required' ?></dd></div><div><dt>Assets</dt><dd><?= (int) $item['assetCount'] ?> · revision <?= (int) $device->inventory_revision ?></dd></div><div><dt>Last seen</dt><dd><?= $device->last_seen_at ? esc($device->last_seen_at->format('Y-m-d H:i:s')) . ' UTC' : 'Never' ?></dd></div><?php if ($device->playback_error): ?><div><dt>Last error</dt><dd><?= esc($device->playback_error) ?></dd></div><?php endif ?></dl>
      <div class="device-links"><a class="btn ghost" href="<?= site_url('control/devices/' . $device->public_id . '/assets') ?>">View Assets</a></div>
      <details><summary>Manage Studio</summary><form method="post" action="<?= site_url('control/devices/' . $device->public_id . '/details') ?>" class="detail-grid"><?= csrf_field() ?><label>Studio name<input name="name" value="<?= esc($device->name) ?>" required></label><label>Location<select name="location_id" required><?php foreach ($locations as $candidate): ?><option value="<?= esc($candidate->public_id) ?>" <?= (int) $device->location_id === (int) $candidate->id ? 'selected' : '' ?> <?= $candidate->status !== 'active' && (int) $device->location_id !== (int) $candidate->id ? 'disabled' : '' ?>><?= esc($candidate->name) ?><?= $candidate->status !== 'active' ? ' — inactive' : '' ?></option><?php endforeach ?></select></label><label>Timezone<input name="timezone" value="<?= esc($device->timezone) ?>"></label><button class="btn ghost" type="submit">Save details</button></form></details>
      <?php if (in_array($device->status, ['pending', 'active'], true)): ?><form method="post" action="<?= site_url('control/devices/' . $device->public_id . '/assignment') ?>" class="assignment-form"><?= csrf_field() ?><select name="assigned_user_id"><option value="">Unassigned</option><?php foreach ($operators as $operator): ?><option value="<?= $operator->id ?>" <?= (int) $device->assigned_user_id === (int) $operator->id ? 'selected' : '' ?>><?= esc($operator->name) ?></option><?php endforeach ?></select><button class="btn ghost" type="submit">Update operator</button></form><?php endif ?>
      <?php if ($device->status === 'active'): ?><form method="post" action="<?= site_url('control/devices/' . $device->public_id . '/revoke') ?>" class="lifecycle-form" onsubmit="return confirm('Revoke this Studio? Its Player will return to pairing.')"><?= csrf_field() ?><button class="btn danger" type="submit">Revoke Studio</button></form><?php endif ?>
    </article>
  <?php endforeach ?></div><?php endif ?>
</section>
<section class="card revoked-section"><div class="card-heading"><div><p>REVOKED</p><h2>Revoked Studios</h2></div><span class="count"><?= count($revokedDevices) ?> Studios</span></div><p class="muted">Revoked Studios cannot connect or send heartbeat. Permanent deletion is available only here.</p>
  <?php if ($revokedDevices === []): ?><div class="empty">No revoked Studios.</div><?php else: ?><div class="device-grid"><?php foreach ($revokedDevices as $item): $device = $item['entity']; ?><article class="device-card revoked"><div class="device-title"><span class="device-icon">×</span><div><strong><?= esc($device->name) ?></strong><small><?= esc($item['location']?->name ?: $device->location ?: 'No Location') ?></small></div><span class="badge revoked">REVOKED</span></div><dl><div><dt>Device ID</dt><dd><?= esc($device->public_id) ?></dd></div><div><dt>Previously assigned</dt><dd><?= esc($item['assignedName']) ?></dd></div><div><dt>Last seen</dt><dd><?= $device->last_seen_at ? esc($device->last_seen_at->format('Y-m-d H:i:s')) . ' UTC' : 'Never' ?></dd></div></dl><form method="post" action="<?= site_url('control/devices/' . $device->public_id . '/delete') ?>" class="lifecycle-form" onsubmit="return confirm('Permanently delete this revoked Studio? This action cannot be undone.')"><?= csrf_field() ?><button class="btn danger" type="submit">Delete Permanently</button></form></article><?php endforeach ?></div><?php endif ?>
</section>
<?= view('web/_layout_bottom') ?>
