<?= view('web/_layout_top', get_defined_vars()) ?>
<?php $modalToOpen = (string) (session('modal') ?: (old('_modal_context') === 'create-location' ? 'create-location-modal' : '')); ?>
<section class="card" data-cms-directory data-endpoint="<?= site_url('control/locations/collection') ?>" data-count-label="Locations" data-empty-title="No matching Locations" data-empty-message="Change the filters or add a new Location." data-skeleton-variant="card" data-skeleton-columns="2" <?= $modalToOpen !== '' && $modalToOpen !== 'create-location-modal' ? 'data-auto-open="' . esc($modalToOpen, 'attr') . '"' : '' ?>>
  <div class="cms-page-toolbar"><div><p>LOCATION DIRECTORY</p><h2>Locations and Studios</h2><span>Organize cinema sites, then manage the Studios inside each Location.</span></div><div class="cms-toolbar-actions"><span class="count" data-cms-directory-count><?= (int) $locationTotal ?> Locations</span><button class="btn primary" type="button" data-cms-modal-open="create-location-modal">+ Add Location</button></div></div>
  <div>
    <form method="get" action="<?= site_url('control/locations') ?>" class="filter-row" data-cms-directory-filter><input type="search" name="q" value="<?= esc($filters['q']) ?>" placeholder="Search name, code, or address"><select name="status"><option value="">All statuses</option><option value="active" <?= $filters['status'] === 'active' ? 'selected' : '' ?>>Active</option><option value="inactive" <?= $filters['status'] === 'inactive' ? 'selected' : '' ?>>Inactive</option></select><button class="btn primary" type="submit">Apply filters</button><a class="btn ghost" href="<?= site_url('control/locations') ?>">Reset</a></form>
    <div data-cms-directory-collection><div class="location-grid" data-cms-async-items></div><nav data-cms-async-pagination aria-label="Location pages"></nav></div>
  </div>
</section>
<dialog class="cms-action-modal" id="create-location-modal" data-cms-modal <?= $modalToOpen === 'create-location-modal' ? 'data-auto-open="true"' : '' ?>><form method="post" action="<?= site_url('control/locations') ?>" class="cms-modal-shell cms-modal-form"><?= csrf_field() ?><input type="hidden" name="_modal_context" value="create-location"><header class="cms-modal-header"><div><p>ORGANIZATION</p><h2>Add a Location</h2><span>One Location can contain multiple Studios.</span></div><button class="cms-modal-x" type="button" data-cms-modal-close>×</button></header><div class="cms-modal-body cms-form-grid"><label>Location name<input name="name" value="<?= esc(old('name')) ?>" maxlength="160" placeholder="Bogor" required autofocus></label><label>Code<input name="code" value="<?= esc(old('code')) ?>" maxlength="24" placeholder="BGR" pattern="[A-Za-z0-9][A-Za-z0-9-]{0,23}" required></label><label>Timezone<input name="timezone" value="<?= esc(old('timezone') ?: 'Asia/Jakarta') ?>" required></label><label>Address <span class="muted">(optional)</span><input name="address" value="<?= esc(old('address')) ?>" maxlength="1000" placeholder="Mall, street, city"></label></div><footer class="cms-modal-footer"><span>Studios can be added immediately after creation.</span><div><button class="btn ghost" type="button" data-cms-modal-close>Cancel</button><button class="btn primary" type="submit">Create Location</button></div></footer></form></dialog>
<?= view('web/_layout_bottom') ?>
