<?= view('web/_layout_top', get_defined_vars()) ?>
<?php $modalToOpen = (string) (session('modal') ?: (old('_modal_context') === 'create-account' ? 'create-account-modal' : '')); ?>
<section class="card" data-cms-directory data-endpoint="<?= site_url('control/operators/collection') ?>" data-count-label="accounts" data-empty-title="No matching accounts" data-empty-message="Change the search, role, or status filters." data-skeleton-variant="row" <?= $modalToOpen !== '' && $modalToOpen !== 'create-account-modal' ? 'data-auto-open="' . esc($modalToOpen, 'attr') . '"' : '' ?>>
  <div class="cms-page-toolbar"><div><p>ACCESS MANAGEMENT</p><h2>CMS accounts</h2><span>Manage administrators, Studio operators, and film distributors.</span></div><div class="cms-toolbar-actions"><span class="count" data-cms-directory-count><?= (int) $accountTotal ?> accounts</span><button class="btn primary" type="button" data-cms-modal-open="create-account-modal">+ Add Account</button></div></div>
  <form method="get" action="<?= site_url('control/operators') ?>" class="filter-row account-filters" data-cms-directory-filter><input type="search" name="q" value="<?= esc($filters['q']) ?>" placeholder="Search name or email"><select name="role"><option value="">All roles</option><option value="admin" <?= $filters['role'] === 'admin' ? 'selected' : '' ?>>Administrator</option><option value="operator" <?= $filters['role'] === 'operator' ? 'selected' : '' ?>>Operator</option><option value="distributor" <?= $filters['role'] === 'distributor' ? 'selected' : '' ?>>Distributor</option></select><select name="status"><option value="">All statuses</option><option value="active" <?= $filters['status'] === 'active' ? 'selected' : '' ?>>Active</option><option value="inactive" <?= $filters['status'] === 'inactive' ? 'selected' : '' ?>>Inactive</option></select><button class="btn primary" type="submit">Search</button><a class="btn ghost" href="<?= site_url('control/operators') ?>">Reset</a></form>
  <div data-cms-directory-collection><div class="account-list" data-cms-async-items></div><nav data-cms-async-pagination aria-label="Account pages"></nav></div>
</section>
<dialog class="cms-action-modal" id="create-account-modal" data-cms-modal <?= $modalToOpen === 'create-account-modal' ? 'data-auto-open="true"' : '' ?>><form method="post" action="<?= site_url('control/operators') ?>" class="cms-modal-shell cms-modal-form"><?= csrf_field() ?><input type="hidden" name="_modal_context" value="create-account"><header class="cms-modal-header"><div><p>NEW ACCOUNT</p><h2>Add a CMS account</h2><span>Operators control assigned Studios; distributors submit films.</span></div><button class="cms-modal-x" type="button" data-cms-modal-close>×</button></header><div class="cms-modal-body cms-form-grid"><label>Name<input name="name" value="<?= esc(old('name')) ?>" maxlength="120" required autofocus></label><label>Email<input type="email" name="email" value="<?= esc(old('email')) ?>" required></label><label>Role<select name="role"><option value="operator" <?= old('role', 'operator') === 'operator' ? 'selected' : '' ?>>Operator</option><option value="distributor" <?= old('role') === 'distributor' ? 'selected' : '' ?>>Distributor</option><option value="admin" <?= old('role') === 'admin' ? 'selected' : '' ?>>Administrator</option></select></label><label>Initial password<input type="password" name="password" minlength="12" required autocomplete="new-password"></label></div><footer class="cms-modal-footer"><span>Password must contain at least 12 characters.</span><div><button class="btn ghost" type="button" data-cms-modal-close>Cancel</button><button class="btn primary" type="submit">Create Account</button></div></footer></form></dialog>
<?= view('web/_layout_bottom') ?>
